# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
# matrix:
#   allow_failures:
#     - 0.7
#   fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.develop(Pkg.PackageSpec(url="https://github.com/jlapeyre/MethodInSrc.jl")); Pkg.develop(Pkg.PackageSpec(url="https://github.com/JuliaArrays/FillArrays.jl")); Pkg.clone(pwd()); Pkg.build("IdentityMatrix"); Pkg.test("IdentityMatrix"; coverage=true)'
  
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
